/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelMenuPanel.java
 *
 * Created on Oct 4, 2010, 3:05:09 PM
 */

package planetsudo.view.menu;

import planetsudo.level.AbstractLevel;

/**
 *
 * @author divine
 */
public class LevelMenuPanel extends javax.swing.JPanel {

    /** Creates new form LevelMenuPanel */
    public LevelMenuPanel() {
        initComponents();
    }

	public void setLevel(AbstractLevel level) {
		nameAndTimeLabel.setText(level.getName()+" [00:00]");
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameAndTimeLabel = new javax.swing.JLabel();

        setOpaque(false);

        nameAndTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameAndTimeLabel.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameAndTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameAndTimeLabel))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameAndTimeLabel;
    // End of variables declaration//GEN-END:variables

}
