/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TeamPanel.java
 *
 * Created on Jun 30, 2010, 6:13:25 PM
 */

package planetsudo.view.menu;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.Timer;
import planetsudo.game.Team;
import planetsudo.level.levelobjects.Mothership;

/**
 *
 * @author noxus
 */
public class TeamMenuPanel extends javax.swing.JPanel implements PropertyChangeListener, ActionListener {
	
	private Team team;
	private Timer timer;

    /** Creates new form TeamPanel */
    public TeamMenuPanel() {
        this.initComponents();
		this.mothershipFuelProgressBar.setMinimum(0);
		this.mothershipFuelProgressBar.setMaximum(Mothership.DEFAULT_START_FUEL);
		this.timer = new Timer(300, this);
		
    }
	
	private void updateComponents() {
		teamColorPanel.setBackground(team.getTeamColor());
		teamNameLabel.setText(team.getName());
		mothershipFuelProgressBar.setForeground(Color.BLACK);
		mothershipFuelProgressBar.setValue(team.getMothership().getFuel());
		teamAgentLabel.setText(team.getAgentCount()+" viecher");
		shieldProgressBar.setValue(team.getMothership().getShieldForce());
		teamResourceLabel.setText(team.getPoints()+"");
		updateFuelProgressBar();
		updateShieldProgressBar();

		String memberList = "<html>";
		for(String member : team.getMembers()) {
			memberList += member+"<br />";
		}
		memberList += "</html>";
		teamMemberLabel.setText(memberList);
	}

//	private int add(int a, int b) {
//		return a+b;
//	}
//
//	private int alter;
//
//	public int getAlter() {
//		return alter;
//	}
//
//	public void setAlter(int alterNeu) {
//		this.alter = alterNeu;
//	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamNameLabel = new javax.swing.JLabel();
        teamMothershipPanel = new javax.swing.JPanel();
        mothershipFuelProgressBar = new javax.swing.JProgressBar();
        shieldProgressBar = new javax.swing.JProgressBar();
        teamColorPanel = new javax.swing.JPanel();
        teamRessourceLabel2 = new javax.swing.JLabel();
        teamResourceLabel = new javax.swing.JLabel();
        teamMemberLabel2 = new javax.swing.JLabel();
        teamMemberLabel = new javax.swing.JLabel();
        teamAgentLabel2 = new javax.swing.JLabel();
        teamAgentLabel = new javax.swing.JLabel();

        setOpaque(false);

        teamNameLabel.setText("Team");

        teamMothershipPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mutterschiff"));
        teamMothershipPanel.setOpaque(false);

        mothershipFuelProgressBar.setString("Treibstoff");
        mothershipFuelProgressBar.setStringPainted(true);

        shieldProgressBar.setString("Schutzschild");
        shieldProgressBar.setStringPainted(true);

        javax.swing.GroupLayout teamMothershipPanelLayout = new javax.swing.GroupLayout(teamMothershipPanel);
        teamMothershipPanel.setLayout(teamMothershipPanelLayout);
        teamMothershipPanelLayout.setHorizontalGroup(
            teamMothershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamMothershipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teamMothershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shieldProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(mothershipFuelProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );
        teamMothershipPanelLayout.setVerticalGroup(
            teamMothershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamMothershipPanelLayout.createSequentialGroup()
                .addComponent(mothershipFuelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shieldProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        teamColorPanel.setBackground(new java.awt.Color(51, 102, 255));
        teamColorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        teamColorPanel.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout teamColorPanelLayout = new javax.swing.GroupLayout(teamColorPanel);
        teamColorPanel.setLayout(teamColorPanelLayout);
        teamColorPanelLayout.setHorizontalGroup(
            teamColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        teamColorPanelLayout.setVerticalGroup(
            teamColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        teamRessourceLabel2.setText("Punkte:");

        teamResourceLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teamResourceLabel.setText("0");

        teamMemberLabel2.setText("Entwickler:");

        teamMemberLabel.setText("Member");
        teamMemberLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        teamAgentLabel2.setText("Agenten:");

        teamAgentLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teamAgentLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teamMothershipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(teamColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teamNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(teamAgentLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamMemberLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamRessourceLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamAgentLabel)
                            .addComponent(teamMemberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(teamResourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teamNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teamMothershipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamRessourceLabel2)
                    .addComponent(teamResourceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamAgentLabel2)
                    .addComponent(teamAgentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamMemberLabel2)
                        .addGap(211, 211, 211))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamMemberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

	
	public void setTeam(Team team) {
		if(team != null) {
			team.removePropertyChangeListener(this);
			team.getMothership().removePropertyChangeListener(this);
		}
		this.team = team;
		team.addPropertyChangeListener(this);
		team.getMothership().addPropertyChangeListener(this);
		updateComponents();
		timer.stop();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar mothershipFuelProgressBar;
    private javax.swing.JProgressBar shieldProgressBar;
    private javax.swing.JLabel teamAgentLabel;
    private javax.swing.JLabel teamAgentLabel2;
    private javax.swing.JPanel teamColorPanel;
    private javax.swing.JLabel teamMemberLabel;
    private javax.swing.JLabel teamMemberLabel2;
    private javax.swing.JPanel teamMothershipPanel;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JLabel teamResourceLabel;
    private javax.swing.JLabel teamRessourceLabel2;
    // End of variables declaration//GEN-END:variables

	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		if(evt.getPropertyName().equals(Mothership.FUEL_STATE_CHANGE)) {
			mothershipFuelProgressBar.setValue((Integer) evt.getNewValue());
			updateFuelProgressBar();
		} else if(evt.getPropertyName().equals(Mothership.SHIELD_STATE_CHANGE)) {
			shieldProgressBar.setValue((Integer) evt.getNewValue());
			updateShieldProgressBar();
		} else if(evt.getPropertyName().equals(Team.POINT_STATE_CHANGE)) {
			teamResourceLabel.setText(evt.getNewValue().toString());
		}
	}
	
	private void updateFuelProgressBar() {

		mothershipFuelProgressBar.setString("Treibstoff " + (int) (mothershipFuelProgressBar.getPercentComplete() * 100) + "%");
			if(mothershipFuelProgressBar.getPercentComplete() < 0.25) {
				timer.start();
			}
		int green, red;
		if (mothershipFuelProgressBar.getPercentComplete() >= 0.5) {
			red = (int) (255 - (255 * (mothershipFuelProgressBar.getPercentComplete() - 0.5) * 2));
			green = 255;
		} else {
			red = 255;
			green = (int) (255 * (mothershipFuelProgressBar.getPercentComplete()) * 2);
		}
		mothershipFuelProgressBar.setForeground(new Color(red, green, 0));
	}

	private void updateShieldProgressBar() {

		shieldProgressBar.setString("Schutzschild " + (int) (shieldProgressBar.getPercentComplete() * 100) + "%");
			if(shieldProgressBar.getPercentComplete() < Mothership.BURNING_MOTHERSHIP/100) {
				timer.start();
			}
		int blue, red;
		if (shieldProgressBar.getPercentComplete() >= 0.5) {
			red = (int) (255 - (255 * (shieldProgressBar.getPercentComplete() - 0.5) * 2));
			blue = 255;
		} else {
			red = 255;
			blue = (int) (255 * (shieldProgressBar.getPercentComplete()) * 2);
		}
		shieldProgressBar.setForeground(new Color(red, 0, blue));
	}

	private boolean blink;

	@Override
	public void actionPerformed(ActionEvent e) {
		if(shieldProgressBar.getPercentComplete() < Mothership.BURNING_MOTHERSHIP/100) {
			if(blink) {
				shieldProgressBar.setForeground(Color.BLACK);
			} else {
				updateShieldProgressBar();
			}
		}

		if(mothershipFuelProgressBar.getPercentComplete() < 0.25) {
			if(blink) {
				mothershipFuelProgressBar.setForeground(Color.BLACK);
			} else {
				updateFuelProgressBar();
			}
		}
		blink = !blink;

		if(mothershipFuelProgressBar.getPercentComplete() > 0.25 && shieldProgressBar.getPercentComplete() > Mothership.BURNING_MOTHERSHIP/100) {
			timer.stop();
			updateShieldProgressBar();
			updateFuelProgressBar();
		}
	}
}
