/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelDisplayPanel.java
 *
 * Created on Jun 19, 2010, 1:15:02 PM
 */

package planetmesserlost.view.level;

import planetmesserlost.level.Level;
import view.components.draw.ResourceDisplayPanel;

/**
 *
 * @author divine
 */
public class LevelDisplayPanel extends ResourceDisplayPanel<LevelPanel> {

    /** Creates new form LevelDisplayPanel */
    public LevelDisplayPanel() {
        initComponents();
    }
	
	public void setLevel(Level level) {
		setVisibleResourcePanel(new LevelPanel(level, this));
	}



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
