/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * LevelTitleLoadingPanel.java
 *
 * Created on Oct 6, 2010, 11:53:08 AM
 */
package org.openbase.planetsudo.view.loading

import org.openbase.planetsudo.game.GameManager.Companion.gameManager
import java.awt.Color
import javax.swing.GroupLayout
import javax.swing.JLabel
import javax.swing.JPanel
import javax.swing.SwingConstants

/**
 * @author [Divine Threepwood](mailto:divine@openbase.org)
 */
class LevelTitleLoadingPanel : JPanel() {
    fun updateDynamicComponents() {
        titleLabel!!.text = "Loading " + gameManager.level!!.name
        background = gameManager.level!!.color
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        titleLabel = JLabel()

        background = Color(0, 0, 0)

        titleLabel!!.horizontalAlignment = SwingConstants.CENTER
        titleLabel!!.text = "Loading Level"

        val layout = GroupLayout(this)
        this.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    GroupLayout.Alignment.TRAILING,
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE.toInt())
                )
        )
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var titleLabel: JLabel? = null // End of variables declaration//GEN-END:variables

    /**
     * Creates new form LevelTitleLoadingPanel
     */
    init {
        initComponents()
    }
}
