/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * MenuLoadingPanel.java
 *
 * Created on Oct 6, 2010, 11:55:22 AM
 */
package org.openbase.planetsudo.view.loading

import javax.swing.GroupLayout
import javax.swing.JPanel

/**
 * @author [Divine Threepwood](mailto:divine@openbase.org)
 */
class MenuLoadingPanel : JPanel() {
    /**
     * Creates new form MenuLoadingPanel
     */
    init {
        initComponents()
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        val layout = GroupLayout(this)
        this.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 852, Short.MAX_VALUE.toInt())
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 59, Short.MAX_VALUE.toInt())
        )
    } // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
