/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * HelpFrame.java
 *
 * Created on Oct 10, 2010, 5:13:20 PM
 */
package org.openbase.planetsudo.view.menu

import org.openbase.jul.exception.CouldNotPerformException
import org.openbase.jul.exception.printer.ExceptionPrinter
import org.openbase.jul.visual.swing.image.ImageLoader
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.awt.EventQueue
import java.awt.Font
import javax.swing.*

/**
 *
 * @author [Divine Threepwood](mailto:divine@openbase.org)
 */
class HelpFrame : JFrame() {
    private val logger: Logger = LoggerFactory.getLogger(javaClass)

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        jLabel1 = JLabel()
        jLabel2 = JLabel()
        jLabel3 = JLabel()
        jLabel4 = JLabel()
        jLabel5 = JLabel()
        jLabel6 = JLabel()
        jLabel7 = JLabel()
        jLabel8 = JLabel()
        jLabel9 = JLabel()
        jLabel10 = JLabel()
        logoDisplayLabel = JLabel()
        jLabel12 = JLabel()
        jLabel13 = JLabel()
        jLabel11 = JLabel()
        jLabel14 = JLabel()
        jLabel15 = JLabel()

        defaultCloseOperation = DISPOSE_ON_CLOSE
        title = "Über PlanetSudo"
        isAlwaysOnTop = true
        isResizable = false

        jLabel1!!.text = "Projekt:"

        jLabel2!!.font = Font("Dialog", 1, 14) // NOI18N
        jLabel2!!.icon = ImageIcon("res/img/agent.png")
        jLabel2!!.text = "PlanetSudo 3"

        jLabel3!!.text = "Entwickler:"

        jLabel4!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel4!!.text = "Divine [Marian Pohling] divine@openbase.org"

        jLabel5!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel5!!.text = "Noxus [Marco Wellmann] Marco.Wellmann@gmx.de"

        jLabel6!!.text = "Veröffentlichung:"

        jLabel7!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel7!!.text = "<html>PlanetSudo 1 (2010)<br>PlanetSudo 2 (2013)<br>PlanetSudo 3 (2016)</html>"

        jLabel8!!.text = "Entwicklungszeit:"

        jLabel9!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel9!!.text = "6 Monate"

        jLabel10!!.font = Font("Dialog", 2, 14) // NOI18N
        jLabel10!!.text =
            "<html><div align=\"justify\"><b>PlanetSudo</b> wurde im Rahmen des 26. 32. & 38. Computerwochenendes der ev. Jugendarbeit in Halle (Westf.) entwickelt. Das Lernziel besteht darin den Teilnehmern zwischen 16 und 25 Jahren einen Einblick in das Design und die Implementierung primitiver Verhaltensweisen zu geben welche im Zusammenspiel ein komplexes Verhalten erzeugen. Das Projekt endet mit einer kurzen Präsentation der erstellten Regeln und einer Reflexion der entwickelten Verhaltensweisen anhand eines Turniers.</dev></html>"
        jLabel10!!.verticalAlignment = SwingConstants.TOP
        jLabel10!!.verticalTextPosition = SwingConstants.TOP

        logoDisplayLabel!!.horizontalAlignment = SwingConstants.RIGHT
        logoDisplayLabel!!.verticalAlignment = SwingConstants.TOP
        logoDisplayLabel!!.isFocusable = false
        logoDisplayLabel!!.horizontalTextPosition = SwingConstants.RIGHT
        logoDisplayLabel!!.verticalTextPosition = SwingConstants.TOP

        jLabel12!!.text = "Lizenz:"

        jLabel13!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel13!!.text = "GNU General Public License"

        jLabel11!!.text = "Designer:"

        jLabel14!!.text = "Copyright:"

        jLabel15!!.font = Font("Dialog", 0, 12) // NOI18N
        jLabel15!!.text = "<html>&copy; 2009 - 2016 openbase.org</html>"

        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(
                                    jLabel10,
                                    GroupLayout.Alignment.TRAILING,
                                    GroupLayout.DEFAULT_SIZE,
                                    901,
                                    Short.MAX_VALUE.toInt()
                                )
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                    layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(
                                                            jLabel8,
                                                            GroupLayout.Alignment.TRAILING,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE.toInt()
                                                        )
                                                        .addComponent(
                                                            jLabel6,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE.toInt()
                                                        )
                                                        .addComponent(
                                                            jLabel3,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE.toInt()
                                                        )
                                                        .addComponent(
                                                            jLabel1,
                                                            GroupLayout.Alignment.TRAILING,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            134,
                                                            Short.MAX_VALUE.toInt()
                                                        )
                                                        .addComponent(
                                                            jLabel11,
                                                            GroupLayout.Alignment.TRAILING,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE.toInt()
                                                        )
                                                )
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel14)
                                        )
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                    layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(220, 220, 220)
                                                )
                                                .addGroup(
                                                    layout.createSequentialGroup()
                                                        .addGroup(
                                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(
                                                                    jLabel5,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE.toInt()
                                                                )
                                                                .addComponent(
                                                                    jLabel9,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE.toInt()
                                                                )
                                                                .addComponent(
                                                                    jLabel13,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE.toInt()
                                                                )
                                                                .addComponent(jLabel7)
                                                                .addComponent(
                                                                    jLabel4,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE.toInt()
                                                                )
                                                                .addComponent(
                                                                    jLabel2,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE.toInt()
                                                                )
                                                        )
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(
                                                            logoDisplayLabel,
                                                            GroupLayout.PREFERRED_SIZE,
                                                            208,
                                                            GroupLayout.PREFERRED_SIZE
                                                        )
                                                )
                                        )
                                )
                        )
                        .addContainerGap()
                )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addGroup(
                                    layout.createSequentialGroup()
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                        )
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel11)
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(
                                                    jLabel7,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    GroupLayout.DEFAULT_SIZE,
                                                    GroupLayout.PREFERRED_SIZE
                                                )
                                        )
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                        )
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel13)
                                        )
                                )
                                .addComponent(
                                    logoDisplayLabel,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE.toInt()
                                )
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(
                            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(
                                    jLabel15,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE
                                )
                        )
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE.toInt())
                        .addContainerGap()
                )
        )

        pack()
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var jLabel1: JLabel? = null
    private var jLabel10: JLabel? = null
    private var jLabel11: JLabel? = null
    private var jLabel12: JLabel? = null
    private var jLabel13: JLabel? = null
    private var jLabel14: JLabel? = null
    private var jLabel15: JLabel? = null
    private var jLabel2: JLabel? = null
    private var jLabel3: JLabel? = null
    private var jLabel4: JLabel? = null
    private var jLabel5: JLabel? = null
    private var jLabel6: JLabel? = null
    private var jLabel7: JLabel? = null
    private var jLabel8: JLabel? = null
    private var jLabel9: JLabel? = null
    private var logoDisplayLabel: JLabel? = null // End of variables declaration//GEN-END:variables

    /**
     * Creates new form HelpFrame
     */
    init {
        instance = this
        initComponents()
        try {
            logoDisplayLabel!!.icon = ImageIcon(ImageLoader.getInstance().loadImage("img/PlanetSudoLogoMedium.png"))
        } catch (ex: CouldNotPerformException) {
            ExceptionPrinter.printHistory(CouldNotPerformException("Could not display image", ex), logger)
        }
        setLocation(300, 300)
    }

    companion object {
        private var instance: HelpFrame? = null

        @Synchronized
        fun display() {
            if (instance == null) {
                EventQueue.invokeLater { HelpFrame().isVisible = true }
                Thread.sleep(500)
            } else {
                instance!!.isVisible = true
            }
        }

        /**
         * @param args the command line arguments
         */
        @JvmStatic
        fun main(args: Array<String>) {
            EventQueue.invokeLater { HelpFrame().isVisible = true }
        }
    }
}
