/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LevelTitleLoadingPanel.java
 *
 * Created on Oct 6, 2010, 11:53:08 AM
 */

package org.openbase.planetsudo.view.loading;

import org.openbase.planetsudo.game.GameManager;
import org.openbase.planetsudo.level.AbstractLevel;



/**
 *
 * @author divine
 */
public class LevelTitleLoadingPanel extends javax.swing.JPanel {

    /** Creates new form LevelTitleLoadingPanel */
    public LevelTitleLoadingPanel() {
        initComponents();
    }
	
	public void updateDynamicComponents() {
		titleLabel.setText("Loading "+GameManager.getInstance().getLevel().getName());
		setBackground(GameManager.getInstance().getLevel().getColor());
	}



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Loading Level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
