/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuLoadingPanel.java
 *
 * Created on Oct 6, 2010, 11:55:22 AM
 */

package org.openbase.planetsudo.view.loading;

import org.openbase.planetsudo.game.GameManager;

/**
 *
 * @author divine
 */
public class MenuLoadingPanel extends javax.swing.JPanel {

    /** Creates new form MenuLoadingPanel */
    public MenuLoadingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
