/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigurationPanel.java
 *
 * Created on Jun 17, 2010, 1:02:56 AM
 */
package de.dc.planetsudo.view.configuration;

import de.dc.util.controller.ObjectFileController;
import de.dc.util.data.ImageLoader;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import de.dc.util.logging.Logger;
import de.unibi.agai.clparser.CLParser;
import de.dc.planetsudo.game.GameManager;
import de.dc.planetsudo.game.Team;
import de.dc.planetsudo.level.AbstractLevel;
import de.dc.planetsudo.level.LevelLoader;
import de.dc.planetsudo.main.command.SetTeamPathCommand;
import de.dc.planetsudo.view.MainGUI;
import javax.swing.SwingWorker;

/**
 *
 * @author divine
 */
public class ConfigurationPanel extends javax.swing.JPanel {

	private Team defaultTeam;

	/**
	 * Creates new form ConfigurationPanel
	 */
	public ConfigurationPanel() {
		initComponents();
		try {
			logoLabel.setIcon(new ImageIcon(ImageLoader.getInstance().loadImage("res/img/PlanetSudoLogoMedium.png")));
		} catch (IOException ex) {
			Logger.warn(this, "Could not display image");
		}
		initDynamicComponents();
	}

	private void initDynamicComponents() {
		LevelChooserComboBox.removeAllItems();
		for (String levelName : LevelLoader.getInstance().getLevelNameSet()) {
			LevelChooserComboBox.addItem(levelName);
		}
		updateTeamList();
		loadDefaultTeam();
	}

	public void updateTeamList() {

		teamAComboBox.removeAllItems();
		teamBComboBox.removeAllItems();
		defaultTeamComboBox.removeAllItems();

		File teamFolder = CLParser.getAttribute(SetTeamPathCommand.class).getValue();
		if (!teamFolder.exists()) {
			Logger.error(this, "Could not find team folder! ");
			return;
		}
		String[] teamClassNameList = teamFolder.list();
		if (teamClassNameList == null) {
			Logger.error(this, "Team folder is empty!!");
			return;
		}
		Team tmpTeam;
		for (String teamClassName : teamClassNameList) {
			if (teamClassName.endsWith(".team")) {
				String teamStringID = teamClassName.replace(".team", "");

				try {
					ObjectFileController<Team> readerWriter = new ObjectFileController<Team>(CLParser.getAttribute(SetTeamPathCommand.class).getValue() + "/" + teamStringID + ".team");

					tmpTeam = readerWriter.readObject();
					teamAComboBox.addItem(tmpTeam);
					teamBComboBox.addItem(tmpTeam);
					defaultTeamComboBox.addItem(tmpTeam);
				} catch (Exception ex) {
					Logger.error(this, "Could not find team " + teamClassName + "!", ex);
					continue;
				}
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel2 = new javax.swing.JPanel();
		LevelChooserComboBox = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		levelPreviewDisplayPanel = new de.dc.planetsudo.view.level.LevelDisplayPanel();
		logoLabel = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		teamBComboBox = new javax.swing.JComboBox();
		teamAComboBox = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		defaultTeamComboBox = new javax.swing.JComboBox();
		setdefaultTeamButton = new javax.swing.JButton();

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Level Einstellungen"));

		LevelChooserComboBox.setMaximumRowCount(20);
		LevelChooserComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
		LevelChooserComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				LevelChooserComboBoxActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(LevelChooserComboBox, 0, 372, Short.MAX_VALUE)
				.addContainerGap()));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
				.addComponent(LevelChooserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jButton1.setText("Ok");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vorschau"));

		javax.swing.GroupLayout levelPreviewDisplayPanelLayout = new javax.swing.GroupLayout(levelPreviewDisplayPanel);
		levelPreviewDisplayPanel.setLayout(levelPreviewDisplayPanelLayout);
		levelPreviewDisplayPanelLayout.setHorizontalGroup(
				levelPreviewDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 433, Short.MAX_VALUE));
		levelPreviewDisplayPanelLayout.setVerticalGroup(
				levelPreviewDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 624, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(levelPreviewDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
				.addComponent(levelPreviewDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));

		logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		logoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

		jButton2.setText("Erstelle Team");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Team Einstellungen"));

		jPanel1.setLayout(new java.awt.GridBagLayout());

		teamBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
		teamBComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				teamBComboBoxActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		jPanel1.add(teamBComboBox, gridBagConstraints);

		teamAComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
		teamAComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				teamAComboBoxActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		jPanel1.add(teamAComboBox, gridBagConstraints);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Team A");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Team B");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
		jPanel1.add(jLabel2, gridBagConstraints);

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("VS");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 15;
		jPanel1.add(jLabel3, gridBagConstraints);

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("StandartTeam"));

		defaultTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
		defaultTeamComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				defaultTeamComboBoxActionPerformed(evt);
			}
		});

		setdefaultTeamButton.setText("Setzen");
		setdefaultTeamButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				setdefaultTeamButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(defaultTeamComboBox, 0, 242, Short.MAX_VALUE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(setdefaultTeamButton)
				.addContainerGap()));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
				.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(defaultTeamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(setdefaultTeamButton))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
				.addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap()));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
				.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jButton2))
				.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
				.addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				.addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
				.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jButton2)
				.addComponent(jButton1))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
				.addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void LevelChooserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelChooserComboBoxActionPerformed
		new SwingWorker() {
			@Override
			protected Object doInBackground() throws Exception {
				if (LevelChooserComboBox.getSelectedItem() != null) {
					AbstractLevel level = LevelLoader.getInstance().loadLevel(LevelChooserComboBox.getSelectedItem().toString());
					GameManager.getInstance().setLevel(level);
					levelPreviewDisplayPanel.setLevel(level);
					levelPreviewDisplayPanel.setOpaque(true);
					levelPreviewDisplayPanel.setBackground(level.getColor());
				}
				return null;
			}
		}.execute();

	}//GEN-LAST:event_LevelChooserComboBoxActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		MainGUI.getInstance().showLoadingPanel();
		GameManager.getInstance().startGame();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		CreateTeamFrame.display();
	}//GEN-LAST:event_jButton2ActionPerformed

	private void teamAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamAComboBoxActionPerformed
		GameManager.getInstance().addTeam((Team) teamAComboBox.getSelectedItem(), GameManager.TeamType.A);
	}//GEN-LAST:event_teamAComboBoxActionPerformed

	private void teamBComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamBComboBoxActionPerformed
		GameManager.getInstance().addTeam((Team) teamBComboBox.getSelectedItem(), GameManager.TeamType.B);
	}//GEN-LAST:event_teamBComboBoxActionPerformed

	private void defaultTeamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultTeamComboBoxActionPerformed
	}//GEN-LAST:event_defaultTeamComboBoxActionPerformed

	private void setDefaultTeam(Team team) {
		setdefaultTeamButton.setForeground(Color.BLACK);
		setdefaultTeamButton.setEnabled(false);
		defaultTeamComboBox.setEnabled(false);
		defaultTeam = team;
		defaultTeamComboBox.setSelectedItem(team);
	}

	private void setdefaultTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setdefaultTeamButtonActionPerformed
		try {
			Team defaultTeamTmp = (Team) defaultTeamComboBox.getSelectedItem();
			setdefaultTeamButton.setForeground(Color.BLACK);
			ObjectFileController<Team> fileWriter = new ObjectFileController<Team>(CLParser.getAttribute(SetTeamPathCommand.class).getDefaultValue().getAbsolutePath() + "/" + defaultTeamTmp.getId() + ".default");
			fileWriter.writeObject(defaultTeamTmp);
			setDefaultTeam(defaultTeamTmp);
		} catch (Exception ex) {
			Logger.error(this, "Could not find team folder!", ex);
			setdefaultTeamButton.setForeground(Color.RED);
			return;
		}

	}//GEN-LAST:event_setdefaultTeamButtonActionPerformed
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox LevelChooserComboBox;
	private javax.swing.JComboBox defaultTeamComboBox;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private de.dc.planetsudo.view.level.LevelDisplayPanel levelPreviewDisplayPanel;
	private javax.swing.JLabel logoLabel;
	private javax.swing.JButton setdefaultTeamButton;
	private javax.swing.JComboBox teamAComboBox;
	private javax.swing.JComboBox teamBComboBox;
	// End of variables declaration//GEN-END:variables

	private void loadDefaultTeam() {
		File teamFolder = CLParser.getAttribute(SetTeamPathCommand.class).getDefaultValue();
		if (!teamFolder.exists()) {
			Logger.error(this, "Could not find team folder! ");
			return;
		}
		String[] teamClassNameList = teamFolder.list();
		if (teamClassNameList == null) {
			Logger.error(this, "Team folder is empty!!");
			return;
		}
		Team tmpTeam;
		for (String teamClassName : teamClassNameList) {
			if (teamClassName.endsWith(".default")) {
				String teamStringID = teamClassName.replace(".default", "");

				try {
					ObjectFileController<Team> readerWriter = new ObjectFileController<Team>(teamFolder.getAbsolutePath() + "/" + teamStringID + ".default");

					tmpTeam = readerWriter.readObject();
					setDefaultTeam(tmpTeam);
				} catch (Exception ex) {
					Logger.warn(this, "Could not find team " + teamClassName + "!", ex);
					continue;
				}
			}
		}
	}

	public Team getDefaultTeam() {
		return defaultTeam;
	}
}
