/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GamePanel.java
 *
 * Created on Jun 17, 2010, 1:03:15 AM
 */

package planetmesserlost.view.game;

import planetmesserlost.game.GameManager;

/**
 *
 * @author divine
 */
public class GamePanel extends javax.swing.JPanel {

    /** Creates new form GamePanel */
    public GamePanel() {
        initComponents();
    }

	public void updateDynamicComponents() {
		levelDisplayPanel.setLevel(GameManager.getInstance().getLevel());
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelDisplayPanel = new planetmesserlost.view.level.LevelDisplayPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout(5, 5));
        add(levelDisplayPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private planetmesserlost.view.level.LevelDisplayPanel levelDisplayPanel;
    // End of variables declaration//GEN-END:variables

}
